{% set name = "autograd-gamma" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f27abb7b8bb9cffc8badcbf59f3fe44a9db39e124ecacf1992b6d952934ac9c4

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - autograd >=1.2.0
    - scipy >=1.2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - autograd_gamma

about:
  home: https://github.com/CamDavidsonPilon/autograd-gamma
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Autograd compatible approximations to the gamma family of functions
  dev_url: https://github.com/CamDavidsonPilon/autograd-gamma

extra:
  recipe-maintainers:
    - mariusvniekerk
    - CamDavidsonPilon
